/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.CtrlVentas;
import Controlador.ctrl_movimientos;
import Modelo.Abono;
import Modelo.DetallesVentas;
import Modelo.Deudas;
import Modelo.Ventas;
import Modelo.movimientosInventario;
import static Vista.FMenu.lbl_totalVenta;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelica Guerrero
 */
public class DetAbono extends javax.swing.JPanel {

    private String tipoVenta = "";
    DefaultTableModel modeloDetalleAbonos = new DefaultTableModel();
    private boolean is_selected = false;
    private int id_abono;
    private static DetAbono instance;

    /**
     * Creates new form PCobrar
     */
    public DetAbono() {
        initComponents();
        Toolkit pantalla=Toolkit.getDefaultToolkit();
        Dimension tamPantalla= pantalla.getScreenSize();
        int alto =tamPantalla.height;
        int ancho = tamPantalla.width;
        setSize(ancho/2,alto/2);
        this.setLayout(new BorderLayout());
        pnl_abono.setVisible(true);
        this.add(pnl_abono, BorderLayout.CENTER); // Agregar pnl_cobrar al centro del panel
        tablaAbonos();
        FMenu fMenu = FMenu.getInstance(); // Asegúrate de que estás obteniendo la instancia correcta de FMenu
        int idClienteEstado = fMenu.getIdClienteEstado();
        cargarDetallesAbonos(idClienteEstado);
    }

    private void tablaAbonos() {
         modeloDetalleAbonos= new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
        modeloDetalleAbonos.addColumn("Fecha");//ID
        modeloDetalleAbonos.addColumn("Cantidad");
        modeloDetalleAbonos.addColumn("Total deuda");
        modeloDetalleAbonos.addColumn("Total abonado");
        modeloDetalleAbonos.addColumn("Deuda pendiente");
        tb_detAbono = new JTable(modeloDetalleAbonos);
        scp_detAbono.setViewportView(tb_detAbono);
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < tb_detAbono.getColumnCount(); i++) {
            tb_detAbono.getColumnModel().getColumn(i).setCellRenderer(centrado);
        }
    }
    public static DetAbono getInstance() {
        if (instance == null) {
            instance = new DetAbono(); // Asegúrate de tener un constructor sin parámetros
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_abono = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        scp_detAbono = new javax.swing.JScrollPane();
        tb_detAbono = new javax.swing.JTable();
        btn_devolver2 = new javax.swing.JButton();

        pnl_abono.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 51));
        jLabel31.setText("Detalle de abonos");

        scp_detAbono.setForeground(new java.awt.Color(255, 255, 255));

        tb_detAbono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_detAbono.setFocusable(false);
        tb_detAbono.setGridColor(new java.awt.Color(153, 153, 153));
        tb_detAbono.setRowHeight(25);
        tb_detAbono.setSelectionBackground(new java.awt.Color(222, 218, 218));
        tb_detAbono.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tb_detAbono.setShowHorizontalLines(true);
        tb_detAbono.getTableHeader().setReorderingAllowed(false);
        scp_detAbono.setViewportView(tb_detAbono);

        btn_devolver2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_devolver2.setText("Regresar");
        btn_devolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolver2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_abonoLayout = new javax.swing.GroupLayout(pnl_abono);
        pnl_abono.setLayout(pnl_abonoLayout);
        pnl_abonoLayout.setHorizontalGroup(
            pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_abonoLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel31)
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_abonoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_devolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_abonoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scp_detAbono, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnl_abonoLayout.setVerticalGroup(
            pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_abonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(btn_devolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_abonoLayout.createSequentialGroup()
                    .addContainerGap(61, Short.MAX_VALUE)
                    .addComponent(scp_detAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_abono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_abono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_devolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolver2ActionPerformed
        // TODO add your handling code here:
        ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();
    }//GEN-LAST:event_btn_devolver2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_devolver2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel pnl_abono;
    private javax.swing.JScrollPane scp_detAbono;
    private javax.swing.JTable tb_detAbono;
    // End of variables declaration//GEN-END:variables
    public void cargarDetallesAbonos(int idCliente) {
    Connection cn = Conexion.Conectar();
    String query = """
        SELECT a.fecha_abono, a.monto_abono, d.total_deuda
        FROM abonos a
        JOIN detalle_deudas d ON a.Id_detalleDeuda = d.id_detalleDeuda
        WHERE d.id_cliente = ? AND d.deuda_pendiente > 0
        ORDER BY a.fecha_abono ASC;
    """;

    try (PreparedStatement st = cn.prepareStatement(query)) {
        st.setInt(1, idCliente);
        ResultSet rs = st.executeQuery();

        // Limpiar el modelo antes de cargar nuevos datos
        modeloDetalleAbonos.setRowCount(0);

        double totalAbonadoAcumulado = 0;
        double totalDeuda = 0;
        
        while (rs.next()) {
            double montoAbono = rs.getDouble("monto_abono");

            if (totalDeuda == 0) {
                totalDeuda = rs.getDouble("total_deuda"); // Se toma solo una vez
            }
            totalAbonadoAcumulado += montoAbono;
            double deudaPendiente = totalDeuda - totalAbonadoAcumulado;

            Object fila[] = new Object[5];
            Timestamp timestamp = rs.getTimestamp("fecha_abono");
            TimeZone timeZone = TimeZone.getDefault();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            sdf.setTimeZone(timeZone);
            String fechaFormateada = sdf.format(timestamp);
            fila[0] = fechaFormateada;
            fila[1] = String.format("%.2f", montoAbono);
            fila[2] = String.format("%.2f", totalDeuda);
            fila[3] = String.format("%.2f", totalAbonadoAcumulado);
            fila[4] = String.format("%.2f", deudaPendiente);

            modeloDetalleAbonos.addRow(fila);
        }

        cn.close();
    } catch (SQLException e) {
        System.out.println("Error al cargar detalles de abonos: " + e);
    }
}



    
}
