/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.CtrlVentas;
import Controlador.ctrl_movimientos;
import Modelo.Abono;
import Modelo.DetallesVentas;
import Modelo.Deudas;
import Modelo.Ventas;
import Modelo.movimientosInventario;
import static Vista.FMenu.lbl_totalVenta;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelica Guerrero
 */
public class PAbono extends javax.swing.JPanel {

    private String tipoVenta = "";
    DefaultTableModel modeloClientes = new DefaultTableModel();
    private boolean is_selected = false;
    private int id_cliente;

    /**
     * Creates new form PCobrar
     */
    public PAbono() {
        initComponents();
        Toolkit pantalla=Toolkit.getDefaultToolkit();
        Dimension tamPantalla= pantalla.getScreenSize();
        int alto =tamPantalla.height;
        int ancho = tamPantalla.width;
        setSize(ancho/2,alto/2);
        this.setLayout(new BorderLayout());
        txt_abono.setText("$0.00");
        pnl_abono.setVisible(true);
        this.add(pnl_abono, BorderLayout.CENTER); // Agregar pnl_cobrar al centro del panel

        // Listeners para seleccionar texto al hacer clic o enfocar
    txt_abono.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            txt_abono.selectAll();
        }
    });

    txt_abono.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            txt_abono.selectAll();
        }
    });

    // 💡 Solicitar foco después de que el panel esté listo
    SwingUtilities.invokeLater(() -> {
        txt_abono.requestFocusInWindow();
        txt_abono.selectAll();
    });
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_abono = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_abono = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        pnl_contado = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txt_abono = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_importe = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lbl_cambio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        pnl_abono.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(210, 225, 235));

        btn_abono.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_abono.setText("Abonar");
        btn_abono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abonoActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_cancelar.setText("Regresar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_abono, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btn_abono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        pnl_contado.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl_contadoLayout = new javax.swing.GroupLayout(pnl_contado);
        pnl_contado.setLayout(pnl_contadoLayout);
        pnl_contadoLayout.setHorizontalGroup(
            pnl_contadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        pnl_contadoLayout.setVerticalGroup(
            pnl_contadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 51));
        jLabel31.setText("Total a abonar");

        txt_abono.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Importe:");

        txt_importe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_importe.setBorder(null);
        txt_importe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_importeKeyReleased(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("Cambio:");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("$");

        lbl_cambio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_cambio.setPreferredSize(new java.awt.Dimension(55, 25));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("$");

        javax.swing.GroupLayout pnl_abonoLayout = new javax.swing.GroupLayout(pnl_abono);
        pnl_abono.setLayout(pnl_abonoLayout);
        pnl_abonoLayout.setHorizontalGroup(
            pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_abonoLayout.createSequentialGroup()
                .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_abonoLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(pnl_contado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_abonoLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel31))
                    .addGroup(pnl_abonoLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(txt_abono, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_abonoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_abonoLayout.createSequentialGroup()
                                .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_abonoLayout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel30))
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_abonoLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1)
                                .addGap(0, 0, 0)
                                .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_importe, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_abonoLayout.setVerticalGroup(
            pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_abonoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel31)
                .addGap(31, 31, 31)
                .addComponent(txt_abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_abonoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel29))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_importe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_abonoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_abonoLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel30)))
                    .addComponent(jLabel2)
                    .addComponent(lbl_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_contado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 1, Short.MAX_VALUE)
                    .addComponent(pnl_abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl_abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

   
    private void btn_abonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abonoActionPerformed
        // TODO add your handling code here:
        cobrarAbono();
        // Cierra el JDialog que contiene este panel
        ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();

        // Accede al id_clienteEstado a través de la instancia de FMenu
        FMenu fMenu = FMenu.getInstance(); // Asegúrate de que estás obteniendo la instancia correcta de FMenu
        int idClienteEstado = fMenu.getIdClienteEstado();

        // Llama al método para actualizar el resumen de la deuda del cliente con la información más reciente
        fMenu.mostrarResumenDeudaCliente(idClienteEstado);
        fMenu.cargarTablaEstadoCuentaFiado(idClienteEstado);
        fMenu.cargarHistorialDeudas();
        DetAbono dabono = DetAbono.getInstance();
        dabono.cargarDetallesAbonos(idClienteEstado);
                    
    }//GEN-LAST:event_btn_abonoActionPerformed

    private void txt_importeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_importeKeyReleased
        // TODO add your handling code here:
        txt_importe.requestFocus();
        cambio();
    }//GEN-LAST:event_txt_importeKeyReleased

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();

    }//GEN-LAST:event_btn_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abono;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_cambio;
    private javax.swing.JPanel pnl_abono;
    private javax.swing.JPanel pnl_contado;
    private javax.swing.JTextField txt_abono;
    public static javax.swing.JTextField txt_importe;
    // End of variables declaration//GEN-END:variables
    private void cambio() {
        // TODO add your handling code here:
        if (!txt_importe.getText().isEmpty()) {

            double cuenta = Double.parseDouble(txt_importe.getText().trim());
            // Obtener el texto de total a cobrar y eliminar cualquier símbolo no numérico
            double totpag = Double.parseDouble(txt_abono.getText().trim().replaceAll("[^\\d.]", ""));
            double cobrar = (cuenta - totpag);
            double cobrar2 = (double) Math.round(cobrar * 100) / 100;
            String cobrarT = String.valueOf(cobrar2);
            lbl_cambio.setText(cobrarT);

        } else {
            lbl_cambio.setText("0.00");
        }
    }
    public void cobrarAbono() {
    int idDetalleDeuda = CtrlVentas.idDetalleDeudaRegistrado;

    if (idDetalleDeuda == -1) {
        JOptionPane.showMessageDialog(null, "Este cliente no tiene una deuda pendiente.", "Advertencia", JOptionPane.WARNING_MESSAGE); 
        return;
    }

    Abono abono = new Abono();
    CtrlVentas ctVentas = new CtrlVentas();
    abono.setId_detalleDeuda(idDetalleDeuda);
    String fechaActual = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());      
    abono.setFecha_abono(fechaActual);
    double totalAbono = Double.parseDouble(txt_abono.getText().trim());
        // Validar importe ingresado
        double importeIngresado;
        try {
            importeIngresado = Double.parseDouble(txt_importe.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un importe válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (importeIngresado < totalAbono) {
            JOptionPane.showMessageDialog(null, "El importe ingresado no puede ser menor al total a abonar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
    try {
        String montoAbono = txt_abono.getText().trim();
        if (!montoAbono.matches("^\\d+(\\.\\d+)?$")) {
            JOptionPane.showMessageDialog(null, "Ingrese números válidos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double montoAbonoF = Double.parseDouble(montoAbono);
        abono.setMonto_abono(montoAbonoF);
        // Verificar la deuda pendiente antes de registrar el abono
        double deudaPendiente = obtenerDeudaPendiente(idDetalleDeuda);
        if (montoAbonoF > deudaPendiente) {
            JOptionPane.showMessageDialog(null, "El abono no puede ser mayor que la deuda pendiente de $" + deudaPendiente," Advertencia", JOptionPane.WARNING_MESSAGE); 
            return;
        }
    } catch (NumberFormatException e) {
         JOptionPane.showMessageDialog(null, "Ingrese un monto válido para el abono.", "Advertencia", JOptionPane.WARNING_MESSAGE); 
    
        return;
    }

    if (ctVentas.registrarAbono(abono)) {
        JOptionPane.showMessageDialog(null, "Abono registrado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "Error al registrar el abono", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private double obtenerDeudaPendiente(int idDetalleDeuda) {
    Connection cn = Conexion.Conectar();
    double deudaPendiente = 0.00;
    String sql = "SELECT deuda_pendiente FROM detalle_deudas WHERE id_detalleDeuda = ?";

    try (PreparedStatement ps = cn.prepareStatement(sql)) {
        ps.setInt(1, idDetalleDeuda);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            deudaPendiente = rs.getDouble("deuda_pendiente");
        }
    } catch (SQLException e) {
        System.out.println("Error al obtener deuda pendiente: " + e);
    }

    return deudaPendiente;
}

    
}
