/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Productos;
import java.awt.Color;
import java.awt.Window;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Angelica Guerrero
 */
public class PBuscarProducto extends javax.swing.JPanel {

    DefaultTableModel modeloProductosB = new DefaultTableModel();

    /**
     * Creates new form PBuscarProducto
     */
    public PBuscarProducto() {
        initComponents();
        FMenu fMenuInstance = FMenu.getInstance(); // Asegúrate de tener un método getInstance() en FMenu
        tablaProductos();
        fMenuInstance.cargar_tablaProductos();

        // Agregar listener de teclado al campo de texto del código del producto
        txt_buscarProductoV.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                    // Transferir el foco a la tabla
                    tb_adProductoB.requestFocus();
                    // Seleccionar la primera fila de la tabla
                    tb_adProductoB.getSelectionModel().setSelectionInterval(0, 0);

                }
            }

        });
        tb_adProductoB.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btn_aceptarActionPerformed(null);
                }
                if (e.getKeyCode() == KeyEvent.VK_E) {
                    btn_aceptarActionPerformed(null);
                }
            }
        });
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_buscarProducto = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        scp_adProductoB = new javax.swing.JScrollPane();
        tb_adProductoB = new javax.swing.JTable();
        txt_buscarProductoV = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        scp_adProductoB.setForeground(new java.awt.Color(255, 255, 255));

        tb_adProductoB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_adProductoB.setFocusable(false);
        tb_adProductoB.setGridColor(new java.awt.Color(153, 153, 153));
        tb_adProductoB.setRowHeight(25);
        tb_adProductoB.setSelectionBackground(new java.awt.Color(222, 218, 218));
        tb_adProductoB.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tb_adProductoB.setShowHorizontalLines(true);
        tb_adProductoB.getTableHeader().setReorderingAllowed(false);
        scp_adProductoB.setViewportView(tb_adProductoB);

        txt_buscarProductoV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_buscarProductoV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarProductoVKeyReleased(evt);
            }
        });

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Regresar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese la descripción del articulo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_buscarProductoV)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(scp_adProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 1217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(454, 454, 454)
                                .addComponent(btn_aceptar)
                                .addGap(29, 29, 29)
                                .addComponent(btn_cancelar))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_buscarProductoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scp_adProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_aceptar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_buscarProductoLayout = new javax.swing.GroupLayout(pnl_buscarProducto);
        pnl_buscarProducto.setLayout(pnl_buscarProductoLayout);
        pnl_buscarProductoLayout.setHorizontalGroup(
            pnl_buscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_buscarProductoLayout.setVerticalGroup(
            pnl_buscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1229, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl_buscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl_buscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void tablaProductos() {
        modeloProductosB = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloProductosB.addColumn("N°");//ID
        modeloProductosB.addColumn("Categoria");
        modeloProductosB.addColumn("Codigo del producto");
        modeloProductosB.addColumn("Descripcion");
        modeloProductosB.addColumn("Unidad");
        modeloProductosB.addColumn("Precio costo");
        modeloProductosB.addColumn("Precio venta");
        modeloProductosB.addColumn("Existencias");
        tb_adProductoB = new JTable(modeloProductosB);
        scp_adProductoB.setViewportView(tb_adProductoB);
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);
        tb_adProductoB.getColumnModel().getColumn(0).setMinWidth(0);
        tb_adProductoB.getColumnModel().getColumn(0).setMaxWidth(0);
        tb_adProductoB.getColumnModel().getColumn(0).setWidth(0);
        for (int i = 0; i < tb_adProductoB.getColumnCount(); i++) {
            tb_adProductoB.getColumnModel().getColumn(i).setCellRenderer(centrado);
        }
        tb_adProductoB.getColumnModel().getColumn(1).setPreferredWidth(80); // Establece el ancho de la columna "Artículos"
        tb_adProductoB.getColumnModel().getColumn(2).setPreferredWidth(130); // Establece el ancho de la columna "Artículos"
        tb_adProductoB.getColumnModel().getColumn(3).setPreferredWidth(300); // Establece el ancho de la columna "Artículos"
        FMenu fMenuInstance = FMenu.getInstance(); // Asegúrate de tener un método getInstance() en FMenu
        fMenuInstance.cargar_tablaProductos();
    }
    private void txt_buscarProductoVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarProductoVKeyReleased
        // TODO add your handling code here:
        // Obtener el texto del campo de texto "txt_buscarCliente" después de quitar los espacios en blanco al inicio y al final
        String buscarProducto = txt_buscarProductoV.getText().trim();
        // Llamar al método "buscarCliente" para buscar los clientes que coincidan con el texto "buscarCliente"
        FMenu fMenuInstance = FMenu.getInstance(); // Asegúrate de tener un método getInstance() en FMenu
        // Aplicar el diseño de tablas definido en el método 'diseñoTablas' de la instancia de FMenu

        DefaultTableModel model = fMenuInstance.buscarProductos(buscarProducto);
        // Actualizar la tabla "tb_adcliente" con el nuevo modelo de datos
        tb_adProductoB.setModel(model);
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        TableColumnModel columnModel = tb_adProductoB.getColumnModel();
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);
        columnModel.getColumn(0).setMinWidth(0);
        columnModel.getColumn(0).setMaxWidth(0);
        columnModel.getColumn(0).setWidth(0);
        for (int i = 0; i < columnModel.getColumnCount(); i++) {
            columnModel.getColumn(i).setCellRenderer(centrado);
        }
        columnModel.getColumn(1).setPreferredWidth(80); // Establece el ancho de la columna "Categoria"
        columnModel.getColumn(2).setPreferredWidth(130); // Establece el ancho de la columna "Codigo del producto"
        columnModel.getColumn(3).setPreferredWidth(300); // Establece el ancho de la columna "Descripcion"
        // Llamar al método "diseñoTbClientes" para configurar el diseño de la tabla "tb_adcliente"
      

    }//GEN-LAST:event_txt_buscarProductoVKeyReleased

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        // Obtener la instancia de FMenu
        FMenu fMenuInstance = FMenu.getInstance(); // Asegúrate de tener un método getInstance() en FMenu

        // Obtener la fila seleccionada en la tabla de productos
        int filaSeleccionada = tb_adProductoB.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto de la tabla");
            return;
        }

        // Obtener el código del producto seleccionado accediendo a la tabla que se está mostrando en la interfaz de usuario
        String codigoProductoSeleccionado = (String) tb_adProductoB.getValueAt(filaSeleccionada, 2);

        // Buscar el producto por código
        Productos productoSeleccionado = fMenuInstance.buscarProductoPorCodigo(codigoProductoSeleccionado);
        if (productoSeleccionado == null) {
            JOptionPane.showMessageDialog(null, "Producto no encontrado");
            return;
        }
         if (productoSeleccionado.getExistencias() <= 0) {
        JOptionPane.showMessageDialog(null, "Este producto no tiene existencias disponibles", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
        // Agregar el producto a la lista de ventas
        fMenuInstance.agregarProductoAVenta(productoSeleccionado);

        // Obtener la ventana que contiene el panel
        Window window = SwingUtilities.getWindowAncestor(this);
        // Cerrar la ventana
        window.dispose();
        fMenuInstance.rqFocus();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        FMenu fMenuInstance = FMenu.getInstance(); // Asegúrate de tener un método getInstance() en FMenu
        fMenuInstance.pnlVentas();
        
        Window window2 = SwingUtilities.getWindowAncestor(this);
        // Cerrar la ventana
        window2.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnl_buscarProducto;
    private javax.swing.JScrollPane scp_adProductoB;
    private javax.swing.JTable tb_adProductoB;
    private javax.swing.JTextField txt_buscarProductoV;
    // End of variables declaration//GEN-END:variables
}
