/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.CtrlUsuario;
import Controlador.CtrlVentas;
import Controlador.ctrl_movimientos;
import Modelo.Abono;
import Modelo.DetallesVentas;
import Modelo.Deudas;
import Modelo.Usuario;
import Modelo.Ventas;
import Modelo.movimientosInventario;
import static Vista.FMenu.lbl_totalVenta;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelica Guerrero
 */
public class PRegistro extends javax.swing.JPanel {

    
    /**
     * Creates new form PCobrar
     */
    public PRegistro() {
        initComponents();
        Toolkit pantalla=Toolkit.getDefaultToolkit();
        Dimension tamPantalla= pantalla.getScreenSize();
        int alto =tamPantalla.height;
        int ancho = tamPantalla.width;
        setSize(ancho/6,alto/6);
        this.setLayout(new BorderLayout());
        pnl_abono.setVisible(true);
        this.add(pnl_abono, BorderLayout.CENTER); // Agregar pnl_cobrar al centro del panel

        
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_abono = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_guardarUs = new javax.swing.JButton();
        btn_guardarUs1 = new javax.swing.JButton();
        text_password = new javax.swing.JPasswordField();

        pnl_abono.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 51));
        jLabel31.setText("Registro de usuarios");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Usuario:");

        text_nombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Contraseña:");

        btn_guardarUs.setBackground(new java.awt.Color(0, 153, 0));
        btn_guardarUs.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_guardarUs.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardarUs.setText("Guardar");
        btn_guardarUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarUsActionPerformed(evt);
            }
        });

        btn_guardarUs1.setBackground(new java.awt.Color(0, 51, 204));
        btn_guardarUs1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_guardarUs1.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardarUs1.setText("Regresar");
        btn_guardarUs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarUs1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_abonoLayout = new javax.swing.GroupLayout(pnl_abono);
        pnl_abono.setLayout(pnl_abonoLayout);
        pnl_abonoLayout.setHorizontalGroup(
            pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_abonoLayout.createSequentialGroup()
                .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_abonoLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel31))
                    .addGroup(pnl_abonoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_abonoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel6))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_abonoLayout.createSequentialGroup()
                                .addComponent(btn_guardarUs1)
                                .addGap(56, 56, 56)
                                .addComponent(btn_guardarUs))
                            .addComponent(text_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(text_password))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnl_abonoLayout.setVerticalGroup(
            pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_abonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(29, 29, 29)
                .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(pnl_abonoLayout.createSequentialGroup()
                        .addComponent(text_password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(pnl_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarUs)
                    .addComponent(btn_guardarUs1))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarUsActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        CtrlUsuario ctUsuario = new CtrlUsuario();

        String nombre = text_nombre.getText().trim();
        String password= text_password.getText().trim();
        if (nombre.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // Validar si el usuario ya existe
    if (ctUsuario.usuarioExiste(nombre)) {
        JOptionPane.showMessageDialog(null, "El usuario ya existe.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
        usuario.setNombre_usuario(nombre);
        usuario.setPassword_usuario(password);

        if (ctUsuario.agregar(usuario)) {
            JOptionPane.showMessageDialog(null, "Registro guardado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            text_nombre.setText("");
            text_password.setText("");
            // Cierra el JDialog que contiene este panel
            ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar usuario", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_guardarUsActionPerformed

    private void btn_guardarUs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarUs1ActionPerformed
        // TODO add your handling code here:
        ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();

    }//GEN-LAST:event_btn_guardarUs1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarUs;
    private javax.swing.JButton btn_guardarUs1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnl_abono;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JPasswordField text_password;
    // End of variables declaration//GEN-END:variables
   

    
}
